name: CI

env:
  MINIMUM_PYTHON: "3.12"
  PYTHON_VERSIONS: '["3.12"]'

on:
  push:
    branches:
      - master
    tags:
      - "**"
  pull_request: {}

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Set up Python
        run: uv python install $MINIMUM_PYTHON

      - name: Install ruff
        run: uv sync --only-group lint

      - name: Run ruff
        run: uv run --no-sync ruff check --output-format=github .

  format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Set up Python
        run: uv python install $MINIMUM_PYTHON

      - name: Install ruff
        run: uv sync --only-group lint

      - name: Run ruff
        run: uv run --no-sync ruff format . --check

  typing:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Set up Python
        run: uv python install $MINIMUM_PYTHON

      - name: Install the project
        run: uv sync --group typing-test --no-dev --all-extras

      - name: Run type checking
        run: uv run --no-sync mypy src/ tests/

  test-lower-bound:
    name: test-lower-bound py${{ matrix.python }} on ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python: ${{ fromJSON(env.PYTHON_VERSIONS) }}

    env:
      PYTHON: ${{ matrix.python }}
      OS: ${{ matrix.os }}

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Set up Python
        run: uv python install ${{ matrix.python}}

      - name: Install the project
        run: uv sync --group test --no-dev --all-extras

      - name: Run tests
        run: COV_CORE_SOURCE=src COV_CORE_CONFIG=pyproject.toml COV_CORE_DATAFILE=.coverage.eager uv run --no-sync pytest tests/

      - name: Deal with coverage
        run: |
          uv run --no-sync coverage html --skip-covered --skip-empty
          uv run --no-sync coverage report --format=markdown >> $GITHUB_STEP_SUMMARY
          uv run --no-sync coverage report --fail-under=100

      - name: Upload HTML report if check failed.
        uses: actions/upload-artifact@v4
        with:
          name: html-report
          path: htmlcov
        if: ${{ failure() }}

  test-upper-bound:
    name: test-upper-bound py${{ matrix.python }} on ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python: ${{ fromJSON(env.PYTHON_VERSIONS) }}

    env:
      PYTHON: ${{ matrix.python }}
      OS: ${{ matrix.os }}

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Set up Python
        run: uv python install ${{ matrix.python}}

      - name: Install the project
        run: uv sync --resolution highest --group test --no-dev --all-extras

      - name: Run tests
        run: uv run --no-sync pytest tests/
